version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test


    steps:

      - checkout: 

      - run:
          name: Check directory to Spring boot
          command: pwd 
    
      - run:
          name: Check and change directory to Spring boot
          command: pwd 
          working_directory: ~/project/BackEnd/spring-boot-api/

      - restore_cache:
          key: circleci-springboot-api-{{ checksum "pom.xml"}}

      - run: mvn dependency:go-offline
          working_directory: ~/project/BackEnd/spring-boot-api/

      - save_cache:
          paths: ~/project/BackEnd/spring-boot-api/.m2
          key: circleci-springboot-api-{{ checksum "pom.xml"}}

      - run: mvn package
          working_directory: ~/project/BackEnd/spring-boot-api/

      - store_test_results:
          path: ~/project/BackEnd/spring-boot-api/target/surefire-reports

      - store_artifacts :
          path: ~/project/BackEnd/spring-boot-api/target/spring-boot-api-0.0.1-SNAPSHOT.jar

