version: 2
jobs:
  build:

    docker:
      - image: circleci/openjdk:8-jdk-stretch
      - image: circleci/postgres:9.6.3-alpine
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test


    steps:

      - checkout
          
      - run:
          name: Check directory to Spring boot
          command: pwd 
    
      - run:
          name: Check files in directory of Spring boot
          command: ls 
          working_directory: ~/project/BackEnd/spring-boot-api/

      - restore_cache:
          keys: 
            - circleci-springboot-api-{{ checksum "~/project/BackEnd/spring-boot-api/pom.xml"}}
            - circleci-springboot-api-

      - run: 
          command: mvn dependency:go-offline
          working_directory: ~/project/BackEnd/spring-boot-api/

      - save_cache:
          paths: 
            - .m2
          key: circleci-springboot-api-{{ checksum "~/project/BackEnd/spring-boot-api/pom.xml"}}

      - run:
          command: mvn package
          working_directory: ~/project/BackEnd/spring-boot-api/

      - store_test_results:
          path: ~/project/BackEnd/spring-boot-api/target/surefire-reports

      - store_artifacts :
          path: ~/project/BackEnd/spring-boot-api/target/spring-boot-api-0.0.1-SNAPSHOT.jar

