version: '3'
services:
  app:
    container_name: com-scrumoftheearth-code-backend
    image: com-scrumoftheearth-code-backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - dbpostgresql